version: "3.9"

services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app/frontend
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend_django/my_app_project
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend_django/my_app_project:/usr/src/app/my_app_project
    env_file:
      - ./.env.dev
    depends_on:
      - my-postgres

  my-postgres:
    image: postgres:14-alpine 
    # Alternatively, use the custom PostgreSQL image:
    # build: 
    #   context: ./postgres
    env_file:
      - ./.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: