version: "3.9"

services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app/frontend
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend_django/my_app_project
      dockerfile: Dockerfile.prod
    command: gunicorn my_app_project.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - ./backend_django/my_app_project:/usr/src/app/my_app_project
    env_file:
      - ./.env.prod
    depends_on:
      - my-postgres

  my-postgres:
    image: postgres:14-alpine 
    # Alternatively, use the custom PostgreSQL image:
    # build: 
    #   context: ./db/postgres
    env_file:
      - ./.env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - backend

volumes:
  postgres_data: